# Generated by Django 5.0.14 on 2026-03-13 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('color', models.CharField(default='#8B6914', help_text='Ex: #8B6914', max_length=7, verbose_name='Cor (hex)')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Descrição Curta')),
                ('date', models.DateTimeField(verbose_name='Data e Hora')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Final')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Local')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Endereço Completo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imagem')),
                ('recurrence', models.CharField(choices=[('none', 'Sem Recorrência'), ('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal')], default='none', max_length=20, verbose_name='Recorrência')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('registration_link', models.URLField(blank=True, verbose_name='Link de Inscrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['date'],
            },
        ),
    ]
