# Generated by Django 5.0.14 on 2026-04-28 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registration'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='event',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.igreja', verbose_name='Igreja'),
        ),
    ]
