# Generated by Django 5.0.14 on 2026-04-30 22:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_category_igreja_event_igreja'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Resumo para o Google (max 160 caracteres). Se vazio, usa a Descrição Curta.', max_length=160, verbose_name='Meta description (SEO)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', validators=[core.validators.validate_image], verbose_name='Imagem'),
        ),
    ]
