[pytest]
DJANGO_SETTINGS_MODULE = church_project.settings_test
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    --cov=core
    --cov=events
    --cov=members
    --cov=ebd
    --cov=courses
    --cov=cells
    --cov=api
    --cov-report=term-missing
    --cov-report=html:htmlcov
    -v
