# Generated by Django 5.0.14 on 2026-03-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(default='fa-church', help_text='Ex: fa-music, fa-child, fa-users', max_length=100, verbose_name='Ícone (Font Awesome class)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Ministério',
                'verbose_name_plural': 'Ministérios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='Igreja Graça e Fé', max_length=200, verbose_name='Nome da Igreja')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Slogan')),
                ('about_text', models.TextField(blank=True, verbose_name='Sobre a Igreja')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Imagem Principal (Hero)')),
                ('hero_title', models.CharField(default='Bem-vindo à nossa Igreja', max_length=200, verbose_name='Título do Hero')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo do Hero')),
            ],
            options={
                'verbose_name': 'Configurações do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Função/Cargo')),
                ('text', models.TextField(verbose_name='Testemunho')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonies/', verbose_name='Foto')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testemunho',
                'verbose_name_plural': 'Testemunhos',
                'ordering': ['-created_at'],
            },
        ),
    ]
