# Generated by Django 5.0.14 on 2026-03-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='hero/slides/', verbose_name='Imagem de Fundo')),
                ('button_text', models.CharField(blank=True, help_text='Ex: Ver Eventos', max_length=80, verbose_name='Texto do Botão')),
                ('button_url', models.CharField(blank=True, help_text='Ex: /eventos/ ou https://...', max_length=200, verbose_name='Link do Botão')),
                ('button_text_2', models.CharField(blank=True, max_length=80, verbose_name='Texto do 2º Botão')),
                ('button_url_2', models.CharField(blank=True, max_length=200, verbose_name='Link do 2º Botão')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Slide do Carrossel',
                'verbose_name_plural': 'Slides do Carrossel',
                'ordering': ['order'],
            },
        ),
    ]
