# Generated by Django 5.0.14 on 2026-03-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ['-created_at'], 'verbose_name': 'Testemunho do Site', 'verbose_name_plural': 'Testemunhos do Site (Página Pública)'},
        ),
    ]
