# Generated by Django 5.0.14 on 2026-03-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_testimony_options'),
        ('core', '0008_gallery'),
    ]

    operations = [
    ]
