# Generated by Django 5.0.14 on 2026-04-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_socialpost_event_sourcetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='church_name',
            field=models.CharField(default='Igreja Assembléia de Deus no Brasil', max_length=200, verbose_name='Nome da Igreja'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Deixe vazio para publicar agora', null=True, verbose_name='Agendar para'),
        ),
    ]
