# Generated by Django 5.0.14 on 2026-04-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_heroslide_modal_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='button_modal_content',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='button_modal_content_2',
        ),
    ]
