# Generated by Django 5.0.14 on 2026-04-28 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_heroslide_button_modal_content_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devotional',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devotionals', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='mediacategory',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_categories', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministries', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_albums', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='igreja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='socialconfig',
            name='igreja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_config', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='pub_date',
            field=models.DateField(verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts_core', to='core.photoalbum', verbose_name='Álbum'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterUniqueTogether(
            name='devotional',
            unique_together={('igreja', 'pub_date')},
        ),
    ]
