# Generated by Django 5.0.14 on 2026-04-30 06:07

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_devotional_igreja_heroslide_igreja_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='hero/slides/', validators=[core.validators.validate_image], verbose_name='Imagem de Fundo'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='media/audio/', validators=[core.validators.validate_audio], verbose_name='Arquivo de Áudio'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf/', validators=[core.validators.validate_document], verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/thumbs/', validators=[core.validators.validate_image], verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery/photos/', validators=[core.validators.validate_image], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/covers/', validators=[core.validators.validate_image], verbose_name='Foto de Capa'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', validators=[core.validators.validate_image], verbose_name='Imagem Principal (Hero)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[core.validators.validate_image], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonies/', validators=[core.validators.validate_image], verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text="Ex: 'nossa-historia' → /p/nossa-historia/", unique=True, verbose_name='Slug (URL)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='pages/covers/', validators=[core.validators.validate_image], verbose_name='Imagem de capa')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('template_name', models.CharField(choices=[('core/page.html', 'Página padrão'), ('core/page_wide.html', 'Página largura total'), ('core/page_landing.html', 'Landing page (sem menu/rodapé)')], default='core/page.html', max_length=60, verbose_name='Template')),
                ('meta_description', models.CharField(blank=True, help_text='Resumo exibido nos resultados do Google (max 160 caracteres)', max_length=160, verbose_name='Meta description (SEO)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta keywords')),
                ('published', models.BooleanField(default=False, verbose_name='Publicada')),
                ('show_in_nav', models.BooleanField(default=False, help_text='Adiciona esta página ao menu de navegação público', verbose_name='Exibir no menu')),
                ('nav_order', models.PositiveSmallIntegerField(default=0, verbose_name='Posição no menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('igreja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tenants.igreja', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['nav_order', 'title'],
            },
        ),
    ]
