# Generated by Django 5.0.14 on 2026-04-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_page_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Resumo para o Google (max 160 caracteres).', max_length=160, verbose_name='Meta description (SEO)'),
        ),
    ]
