# Generated by Django 5.0.14 on 2026-05-02 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_meta_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Sessão')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('page', models.CharField(max_length=500, verbose_name='Página')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('country_code', models.CharField(blank=True, max_length=5, verbose_name='País')),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at', 'session_key'], name='core_sitevi_visited_609723_idx')],
            },
        ),
    ]
