# Generated by Django 5.0.14 on 2026-05-02 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sitevisit'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='tenants.igreja', verbose_name='Igreja'),
        ),
    ]
