# Generated by Django 5.0.14 on 2026-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Igreja')),
                ('slug', models.SlugField(help_text='Usado na URL: minhagreja.seuapp.com.br', unique=True, verbose_name='Slug')),
                ('dominio_proprio', models.CharField(blank=True, help_text='Ex: www.igrejadagraca.com.br (sem https://)', max_length=253, verbose_name='Domínio Próprio')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('plano', models.CharField(choices=[('basic', 'Básico'), ('pro', 'Pro'), ('trial', 'Trial')], default='trial', max_length=10, verbose_name='Plano')),
                ('trial_ate', models.DateField(blank=True, help_text='Data de expiração do período de teste', null=True, verbose_name='Trial até')),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
                'ordering': ['nome'],
            },
        ),
    ]
