# Generated by Django 5.0.14 on 2026-03-19 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbdClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Enunciado')),
                ('explanation', models.TextField(blank=True, verbose_name='Explicação da resposta correta')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EbdTrimester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre'), (4, '4º Trimestre')], verbose_name='Trimestre')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Trimestre')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='ebd/covers/', verbose_name='Capa')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ebd_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimesters', to='ebd.ebdclass', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Trimestre',
                'verbose_name_plural': 'Trimestres',
                'ordering': ['-year', 'quarter'],
                'unique_together': {('ebd_class', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='EbdLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número da Lição')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.TextField(blank=True, help_text='Texto exibido na prévia pública', verbose_name='Resumo público')),
                ('body', models.TextField(blank=True, verbose_name='Conteúdo da aula (texto)')),
                ('video_url', models.URLField(blank=True, verbose_name='Vídeo (YouTube/Vimeo)')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='ebd/audio/', verbose_name='Áudio')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='ebd/pdf/', verbose_name='PDF')),
                ('scripture', models.CharField(blank=True, help_text='Ex: João 3:16-17', max_length=200, verbose_name='Texto Bíblico Base')),
                ('published', models.BooleanField(default=False, verbose_name='Publicada')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ebd.ebdtrimester', verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Lição',
                'verbose_name_plural': 'Lições',
                'ordering': ['order', 'number'],
                'unique_together': {('trimester', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texto da alternativa')),
                ('is_correct', models.BooleanField(default=False, verbose_name='É a correta')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ebd.question', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score', models.PositiveSmallIntegerField(default=70, verbose_name='Nota mínima para aprovação (%)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, help_text='0 = ilimitado', verbose_name='Tentativas permitidas')),
                ('show_answers', models.BooleanField(default=True, verbose_name='Mostrar gabarito após tentativa')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='ebd.ebdlesson', verbose_name='Lição')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ebd.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Pontuação (%)')),
                ('passed', models.BooleanField(verbose_name='Aprovado')),
                ('answers', models.JSONField(default=dict, verbose_name='Respostas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ebd.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Tentativa de Quiz',
                'verbose_name_plural': 'Tentativas de Quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='ebd.ebdlesson', verbose_name='Lição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
                ('attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='ebd.quizattempt', verbose_name='Tentativa')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
