# Generated by Django 5.0.14 on 2026-04-30 22:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebd', '0002_ebdclass_igreja'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebdlesson',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Resumo para o Google (max 160 caracteres). Se vazio, usa o Resumo público.', max_length=160, verbose_name='Meta description (SEO)'),
        ),
        migrations.AlterField(
            model_name='ebdlesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='ebd/audio/', validators=[core.validators.validate_audio], verbose_name='Áudio'),
        ),
        migrations.AlterField(
            model_name='ebdlesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='ebd/pdf/', validators=[core.validators.validate_document], verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='ebdtrimester',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='ebd/covers/', validators=[core.validators.validate_image], verbose_name='Capa'),
        ),
    ]
