# Generated by Django 5.0.14 on 2026-04-28 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_id_alter_course_workload_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_categories', to='tenants.igreja', verbose_name='Igreja'),
        ),
    ]
