# Generated by Django 5.0.14 on 2026-04-30 22:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_igreja_coursecategory_igreja'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Resumo para o Google (max 160 caracteres). Se vazio, usa a Descrição.', max_length=160, verbose_name='Meta description (SEO)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', validators=[core.validators.validate_image], verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/audio/', validators=[core.validators.validate_audio], verbose_name='Áudio'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/pdf/', validators=[core.validators.validate_document], verbose_name='PDF / Material'),
        ),
    ]
