# Generated by Django 5.0.14 on 2026-05-02 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfectStudentSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Concedido em')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfect_seal', to='courses.enrollment', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Selo Nota 10',
                'verbose_name_plural': 'Selos Nota 10',
                'ordering': ['-granted_at'],
            },
        ),
    ]
