# Generated by Django 5.0.14 on 2026-06-15 03:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0002_cell_igreja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cells/covers/', validators=[core.validators.validate_image], verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='cellpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cells/files/', validators=[core.validators.validate_generic_file], verbose_name='Arquivo'),
        ),
    ]
