# Generated by Django 5.0.14 on 2026-03-13 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_heroslide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('icon', models.CharField(default='fa-book', help_text='Ex: fa-book, fa-video, fa-music', max_length=80, verbose_name='Ícone FA')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria de Conteúdo',
                'verbose_name_plural': 'Categorias de Conteúdo',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Texto do Aviso')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Importante'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
            ],
            options={
                'verbose_name': 'Aviso Interno',
                'verbose_name_plural': 'Avisos Internos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExclusiveContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content_type', models.CharField(choices=[('text', 'Texto / Estudo'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('file', 'Arquivo PDF'), ('link', 'Link Externo')], default='text', max_length=20, verbose_name='Tipo')),
                ('body', models.TextField(blank=True, verbose_name='Conteúdo / Descrição')),
                ('video_url', models.URLField(blank=True, verbose_name='URL do Vídeo (YouTube/Vimeo)')),
                ('file', models.FileField(blank=True, null=True, upload_to='members/files/', verbose_name='Arquivo')),
                ('external_link', models.URLField(blank=True, verbose_name='Link Externo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='members/thumbs/', verbose_name='Imagem de Capa')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_content', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.contentcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Conteúdo Exclusivo',
                'verbose_name_plural': 'Conteúdos Exclusivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Ex: Tecladista, Líder, Auxiliar', max_length=150, verbose_name='Função no Ministério')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.ministry', verbose_name='Ministério')),
            ],
            options={
                'verbose_name': 'Membro do Ministério',
                'verbose_name_plural': 'Membros dos Ministérios',
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Foto de Perfil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Sobre mim')),
                ('baptized', models.BooleanField(default=False, verbose_name='Batizado(a)')),
                ('member_since', models.DateField(blank=True, null=True, verbose_name='Membro desde')),
                ('approved', models.BooleanField(default=False, help_text='Marque para liberar acesso à área de membros', verbose_name='Cadastro Aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministries', models.ManyToManyField(blank=True, related_name='member_profiles', through='members.MemberMinistry', to='core.ministry', verbose_name='Ministérios')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Membro',
                'verbose_name_plural': 'Perfis de Membros',
            },
        ),
        migrations.AddField(
            model_name='memberministry',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_ministries', to='members.memberprofile', verbose_name='Membro'),
        ),
        migrations.AlterUniqueTogether(
            name='memberministry',
            unique_together={('profile', 'ministry')},
        ),
    ]
