# Generated by Django 5.0.14 on 2026-03-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_prayerrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ['-created_at'], 'verbose_name': 'Testemunho de Membro', 'verbose_name_plural': 'Testemunhos de Membros (Aprovação)'},
        ),
    ]
