# Generated by Django 5.0.14 on 2026-04-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_culto_presenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='image_consent_date',
            field=models.DateTimeField(blank=True, help_text='Registrado automaticamente no momento do aceite', null=True, verbose_name='Data/hora do consentimento'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='image_consent_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP do dispositivo no momento do aceite (auditoria LGPD)', null=True, verbose_name='IP do consentimento'),
        ),
    ]
