# Generated by Django 5.0.14 on 2026-04-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_memberprofile_image_consent_date_and_more'),
        ('members', '0010_culto_visitantes'),
    ]

    operations = [
    ]
