# Generated by Django 5.0.14 on 2026-04-28 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_merge_20260425_0210'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_categories', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='culto',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultos', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='exclusivecontent',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_contents', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.igreja', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='notice',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='tenants.igreja', verbose_name='Igreja'),
        ),
    ]
