# Generated by Django 5.0.14 on 2026-06-15 03:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_contentcategory_igreja_culto_igreja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusivecontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='members/files/', validators=[core.validators.validate_generic_file], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='exclusivecontent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='members/thumbs/', validators=[core.validators.validate_image], verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/', validators=[core.validators.validate_image], verbose_name='Foto de Perfil'),
        ),
    ]
